name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          git clone https://gitlab.com/tearch-linux/applications-and-tools/teaiso
          cd teaiso
          make && make install
          cd ..
          mkteaiso -c archlinux
          mkteaiso -p archlinux

      - uses: actions/upload-artifact@v2
        with:
            name: output
            path: /output/*
