name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          sudo apt update
          sudo apt install xorriso grub-pc-bin grub-efi mtools make python3 dosfstools e2fsprogs squashfs-tools python3-yaml gcc wget curl unzip xz-utils debootstrap git erofs-utils zstd
          git clone https://gitlab.com/tearch-linux/applications-and-tools/teaiso
          cd teaiso
          sudo make && sudo make install
          cd ..
          sudo mkteaiso -c tearch
          sudo mkteaiso -p tearch
          sudo mkdir -p /output
          sudo mv /var/teaiso/output/* /output/

      - uses: actions/upload-artifact@v2
        with:
            name: output
            path: /output/*
